[project]
name = "dregit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "attrs>=25.1.0",
    "pygit2>=1.17.0",
    "urwid>=2.6.16",
]
[project.scripts]
dregit = "dregit:main"
git-dray = "dregit:main"
